# Generated by Django 4.2.1 on 2023-05-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
